version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "9020:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_BACKEND_URL=https://beat-bouncers-api.studios-tkoh.online
